name: composite action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use my composite action
        uses: ./.likhith-seedarala/repog17
        with:
          node-version: '18'
