name: composite action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Use my composite action
        uses: ./.repog17
        with:
          node-version: '18'
