name: sleep job
on: 
  push:
    branches:
      - main

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run: echo "hello world"
  sleep:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: sleep for
        run: sleep 600
