name: Generate ASCII Artwork
on:
  push:
    branches:
      - main

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cowsay
        run: sudo apt-get update && sudo apt-get install cowsay -y
      - name: Generate ASCII dragon
        run: cowsay -f dragon "Run for cover, I am a DRAGON.... RAWR" >> dragon.txt
      - name: Upload Dragon tezt file
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dration-text-file
          path: dragon.txt
      - name: Pause for 30 seconds
        run: sleep 30

  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon test file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      - name: Verify dragon.txt
        run: grep -i "dragon" dragon.txt

  deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
      - name: Download dragon test file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
      - name: Display file
        run: cat dragon.txt
      - name: Deploy
        run: echo "Deploying"
