name: env-var
on: 
  workflow_dispatch:
    inputs:
      loglevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        env:
          stepVar1: stepvalue1
        run: |
          echo "The value for stepvar1: $stepVar1"
      - name : echo var1
        run: "echo \"the value for repovar1: ${{vars.repovar1 }}\""
      - name : echo sec1
        run : "echo \"the value for reposec1: ${{secrets.reposec1 }}\""
